CREATE TABLE IF NOT EXISTS article_sources (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id VARCHAR(36) NOT NULL,
  name VARCHAR(160) NOT NULL,
  url VARCHAR(500) NOT NULL,
  type ENUM('rss', 'api', 'scraping') NOT NULL DEFAULT 'rss',
  topics JSON NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  last_checked_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_article_sources_public_id (public_id),
  UNIQUE KEY uq_article_sources_url (url),
  KEY idx_article_sources_active (active, type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS articles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id VARCHAR(36) NOT NULL,
  title VARCHAR(220) NOT NULL,
  slug VARCHAR(240) NOT NULL,
  summary TEXT NOT NULL,
  content MEDIUMTEXT NOT NULL,
  category VARCHAR(120) NOT NULL,
  tags JSON NULL,
  origin ENUM('manual', 'external_curated') NOT NULL DEFAULT 'manual',
  status ENUM('draft', 'pending_review', 'published', 'rejected') NOT NULL DEFAULT 'draft',
  source_id BIGINT UNSIGNED NULL,
  source_name VARCHAR(160) NULL,
  source_url VARCHAR(500) NULL,
  image_url VARCHAR(500) NULL,
  published_at DATETIME NULL,
  external_published_at DATETIME NULL,
  reading_minutes INT UNSIGNED NOT NULL DEFAULT 1,
  is_indexable TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_articles_public_id (public_id),
  UNIQUE KEY uq_articles_slug (slug),
  UNIQUE KEY uq_articles_source_url (source_url),
  KEY idx_articles_public (status, published_at),
  KEY idx_articles_origin_status (origin, status),
  KEY idx_articles_category (category),
  CONSTRAINT fk_articles_source FOREIGN KEY (source_id) REFERENCES article_sources(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
